<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="Pkcs11Interop" />
    <ProjectReference Include="../SimplySignAuto.Core/SimplySignAuto.Core.csproj" />
    <ProjectReference Include="../SimplySignAuto.Protocol/SimplySignAuto.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SimplySignAuto.Agent.Tests" />
    <InternalsVisibleTo Include="SimplySignAuto.EndToEnd.Tests" />
  </ItemGroup>
</Project>
