<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <ProjectReference Include="../SimplySignAuto.Core/SimplySignAuto.Core.csproj" />
    <ProjectReference Include="../SimplySignAuto.Protocol/SimplySignAuto.Protocol.csproj" />
  </ItemGroup>
</Project>
